false(1) "ctools"

# NAME

false - exit with status code 1

# SYNOPSIS

*false*

# DESCRIPTION

This program will always exit with status code 1, indicating failure.

# DISCLAIMER

This command is part of ctools and is compatible with POSIX-1.2017, and may
optionally support XSI extensions. This man page is not intended to be a
complete reference, and where it disagrees with the specification, the
specification takes precedence.
