head(1) "ctools"

# NAME

head - print the beginning of files

# SYNOPSIS

*head* [-n _n_] _file_...

# DESCRIPTION

*head* will print the first _n_ lines of each input file specified.

# OPTIONS

*-n* _n_
	Specify the number of lines to print. The default is 10.

# DISCLAIMER

This command is part of ctools and is compatible with POSIX-1.2017, and may
optionally support XSI extensions. This man page is not intended to be a
complete reference, and where it disagrees with the specification, the
specification takes precedence.
