sleep(1) "ctools"

# NAME

sleep - suspend execution for an interval

# SYNOPSIS

*sleep* _time_

# DESCRIPTION

The sleep utility suspends execution for at least the integral
number of seconds specified by the time operand.

# DISCLAIMER

This command is part of ctools and is compatible with POSIX-1.2017, and may
optionally support XSI extensions. This man page is not intended to be a
complete reference, and where it disagrees with the specification, the
specification takes precedence.
