uname(1) "ctools"

# NAME

uname - print the name(s) of the system

# SYNOPSIS

*uname* [-amnrsv]

# DESCRIPTION

*uname* prints the name (or names) of the current system.

# OPTIONS

*-a*
	Print all information.

*-m*
	Print machine (architecture) name.

*-n*
	Print node name (generally this is the node's hostname).

*-r*
	Print release information.

*-s*
	Print sysname (generally this is the name of the kernel).

*-v*
	Print version information.

# DISCLAIMER

This command is part of ctools and is compatible with POSIX-1.2017, and may
optionally support XSI extensions. This man page is not intended to be a
complete reference, and where it disagrees with the specification, the
specification takes precedence.
